### ISSUE TITLE
Documenting abbreviations

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/lexicalresources#1]
We need a section in the documentation discussing best-practice examples of how to deal with abbreviations.

**Comment by anacastrosalgado** [comment]
Like this? An abbreviation [símbolo, abreviatura, sigla] (Ag, Cf., VIP).

<entry> type="abbr">
<form type="lemma">
<orth>Ag</orth>
</form>
 [printed edition]
<gramGrp>símb.</gramGrp>

entry type="abbr">
<form type="lemma">
<orth>VIP</orth>
</form>

<gramGrp>sigla</gramGrp>
<sense>
<cit type="translation">
<quote xml:lang="en">Very ImportantPerson</quote>
<cit type="translation">
<quote xml:lang="pt">(Pessoa Muito Importante)</quote>
</cit>
</cit>
</sense>
</entry>

**Comment by ttasovac** [comment]
This is so old, I have no idea what I meant by it. It's spring cleaning time. We have abbr and expan now (#176), we'll deal with choice separately.
