### ISSUE TITLE
How to encode references to attribute and element classes in the documentation? 

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/lexicalresources#10]
When we discuss elements in the ODD, we use `<gi>` and the element encoded as `<gi>`, for example `<gi>entry</gi> `then automatically becomes a link to the specification in the html generated documentation. 

When we talk about attributes, we use `<att>`, for example: `<att>type</att>` — this will append `@` to the attribute name in the documentation.

I don't know, however, how to encode element and attribute classes: for instance `model.entryPart.top` so that it's automatically transformed to a link to the given class in the documentation. 

@laurentromary?

**Comment by laurentromary** [comment]
OK. The hack I have tested is to use `<ref target="#TEI.model.inter">model.inter</ref>`: the corresponding anchors are automatically generated in the output html with `TEI.` prefix.
