### ISSUE TITLE
entry/gramGrp vs. sense/gramGrp

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/lexicalresources#14]
The narrative section on form has this:

> In cases where headwords are discriminated only on the basis of their orthography (e.g. in English dictionaries which treat conversion pairs of nouns and verbs, such as <hi>run</hi>, as belonging in single entries), <code>entry/gramGrp</code> should not be used, because its role is taken over by the individual <code>sense/gramGrp</code>.

This has led to an extensive exchange:

> **Note**: In some of our dictionaries, the entry has a "summary" of the potential PoS and further specification is done at sense level. So this recommendation would not properly fit. **Note**: I am not sure if I understand this correctly, but if I do, it might be a dictScrap issue. **Note**: i think we may need an example for this — to us it seems that we could have gramgrp both at the entry level and inside senses if that's how you have it in your print dictionary. wouldn't that work for you? **Note**: I think I understood what Katrien meant here. I also think that this restriction will cause an issue when it comes to encode any information which come just after the first pos and is related to the whole lexical entry. Etymology, for example (see the "aid" encoding example)Note: Hi guys, sorry it took so long, but here is an example:There is the preposition and adverb "achter". In the first red box, there is the summary. Below, the semantic descritpion per PoS is done in separate sections in which the grammatical information is repeated. **Note**: I think we should give up the restriction of gathering grammatical information in one spot and encode them just wherever they appear **Note**: [concerning the "achter" example] On the other hand we could also say that such categorial changes as part-of-speech should actually be encoded as separate embedded entries that happen to have some common information encoded in the parent. And here, the commonality is mostly the shared etymology and rather no strictly grammatical features.

The acther example is referring to

![Скриншот 2018-09-02 16.57.00](https://i.imgur.com/4BtZEpf.png)

I've removed the discussion thread from the documentation and I left the suggestion quoted above in the text for the time being, but I need help unpacking this.

So...

1.  is the rule quoted at the beginning of this post still valid? 
2. Katrien, do you now know how you would encode achter in TEI Lex-0?

**Comment by xlhrld** [comment]
In the last comment (in the Google doc discussion quoted above) on that passage I had in mind something along the lines of:
```
<entry>
  <form type="headword"><orth>achter</orth></form>
  <gramGrp><pos>voorz. en bijw.</pos></gramGrp>
  <etym><!-- shared etymology for all parts-of-speech --></etym>
  <entry n="I">
    <gramGrp><pos>Als voorzetsel.</pos></gramGrp>
    <sense>...</sense>
  </entry>
  <entry n="II">
    <gramGrp><pos>Als bijwoord.</pos></gramGrp>
    <sense>...</sense>
  </entry>
  <entry n="III">
    <gramGrp><lbl>In samenstellingen.</lbl></gramGrp>
    <sense>...</sense>
  </entry>
</entry>
```
One could even go so far and also model the compounds presented in section III. as individual embedded entries. Katrien (and others), would this make sense from your perspective?

**Comment by ttasovac** [comment]
@xlhrld —  that's exactly what Laurent and I realized yesterday: the recursive entry may be a blessing for these things. In fact, I would probably prefer that we recommend recursive entries rather than senses for these things... 

This is a big deal and important for v0.7.0. I hope Katrien and Jesse can look into this because this was an important case for them.

**Comment by JessedeDoes** [comment]
I think we still prefer `<sense>` with gramGrp here. 
* It somehow 'feels wrong' to split entries here when there is semantic information to share between the different PoS
* There are indeed examples where the PoS distinction happens at a lower level. Cf. http://gtb.inl.nl/iWDB/search?actie=article&wdb=WNT&id=M022030&lemmodern=groen&betekenis=%22als%20onz%20znw%22&domein=0&conc=true 

Indeed this *could* be treated as a related entry, but is just not the way the WNT is organized
