### ISSUE TITLE
Use white-space: pre-wrap for code to avoid table rows overflow in the documentation

### ISSUE THREAD

**Issue by daliboris** [DARIAH-ERIC/lexicalresources#140]
In the generated documentation in some cases rows/cells of the table overflow width of the screen, as you can see here (Firefox 84.0.2 64bit):
![TEI-LEX-0_Overflow](https://user-images.githubusercontent.com/8056045/104808919-92fd4380-57e9-11eb-8310-6bb28f8f394a.png)

The overflow is caused by `<pre>` elements (mostly `<pre class=" language-xml">`) containing example or schematron definition with long lines.

If you change CSS `white-space` property's value from `pre` to `pre-wrap` (see **prism.css** stylesheet, rule `code[class *= "language-"], pre[class *= "language-"]`), the result can look like this:
![TEI-LEX-0_WRAP](https://user-images.githubusercontent.com/8056045/104809193-b1fcd500-57eb-11eb-980e-35dbe8ba2332.png)

The same approach (`pre-wrap` value for `white-space` property) ia used in the TEI Guidlines (see https://tei-c.org/release/doc/tei-p5-doc/en/html/guidelines.css, rule `pre,div.pre,div.pre_eg,pre.eg,div.eg` on line 382). The documentation for this property can be found on [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space).

Using this value can result in some unwanted/strange rendering of examples, as you can see here (current look followed by proposed):

![TEI-LEX-0_div](https://user-images.githubusercontent.com/8056045/104809713-782dcd80-57ef-11eb-96d9-80d520ad2db6.png)
vs.
![TEI-LEX-0_div_proposed](https://user-images.githubusercontent.com/8056045/104809715-7b28be00-57ef-11eb-9dbc-8e80e6a9094c.png)

![TEI-LEX-0_TEI att datable w3c](https://user-images.githubusercontent.com/8056045/104809730-8f6cbb00-57ef-11eb-958c-2ddf7a791a7d.png)
vs.
![TEI-LEX-0_TEI att datable w3c-proposed](https://user-images.githubusercontent.com/8056045/104809742-9693c900-57ef-11eb-97d7-9400e47b6449.png)

**Comment by ttasovac** [comment]
i don't like the way longer text in paragraphs breaks now but i don't think i can control that. also, to add insult to injury, now we get this:

<img width="577" alt="Снимок экрана 2021-01-16 в 15 15 44" src="https://user-images.githubusercontent.com/5304839/104814202-e3869800-580d-11eb-9056-7c19abeba8a8.png">


but, one thing at a time! 

thanks for the suggestion, boris!
