### ISSUE TITLE
Single or multiple forms for orth & pron: to squeeze or not, that is the question

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/lexicalresources#16]
In the section on Phonetic Variation, we have this example

```xml
<entry xml:id="caramel-en" xml:lang="en-US"> 
  <form type="lemma">  
    <orth>caramel</orth>
    <form type="variant">
      <pron notation="ipa">'keɹə"mɛl</pron>
    </form>
    <form type="variant">
      <pron notation="ipa">'kaɹmɫ̩</pron>
    </form>
  </form>
  <gramGrp>
    <gram type="pos">noun</gram>
  </gramGrp>
  ...
</entry>
```

followed by this conversation:

> **Note**: Is &lt;form type=&quot;lemma&quot;&gt; &lt;orth&gt;caramel&lt;/orth&gt; &lt;pron notation=&quot;ipa&quot;&gt;&apos;ke&#633;&#601;&quot;m&#603;l&lt;/pron&gt; &lt;pron notation=&quot;ipa&quot;&gt;&apos;ka&#633;m&#619;&#809;&lt;/pron&gt; &lt;/form&gt;also a valid option?Do we have general rules when to introduce new &lt;form&gt; subelements when some property is multivalued?What would, for instance, happen if we had a single entry for a noun/adjective? Or, maybe more mainstream, different genders? &lt;form type=&quot;lemma&quot;&gt; &lt;orth&gt;caramel&lt;/orth&gt; &lt;form type=&quot;variant&quot;&gt; &lt;pron notation=&quot;ipa&quot;&gt;&apos;ke&#633;&#601;&quot;m&#603;l&lt;/pron&gt; &lt;/form&gt; &lt;form type=&quot;variant&quot;&gt; &lt;pron notation=&quot;ipa&quot;&gt;&apos;ka&#633;m&#619;&#809;&lt;/pron&gt; &lt;/form&gt; &lt;/form&gt; &lt;gramGrp&gt; &lt;gen&gt;m&lt;/gen&gt; &lt;pos&gt;f&lt;/gen&gt; &lt;/gramGrp&gt;?For multivalued properties Cf. also the lemon fragment at: https://www.w3.org/community/ontolex/wiki/Final_Model_Specification#Forms :lex_privacy a ontolex:LexicalEntry; ontolex:form :form_privacy.:form_privacy a ontolex:Form; ontolex:writtenRep &quot;privacy&quot;@en; ontolex:phoneticRep &quot;&#712;p&#633;&#618;v.&#601;.si&quot;@en-US-fonipa; ontolex:phoneticRep &quot;&#712;p&#633;a&#618;.v&#601;.si&quot;@en-GB-fonipa. 
> **Note**: It seems to me that Jesse&apos;s question about whether to use separate form/pron or whether to squeeze &lt;pron&gt;s into a single &lt;form&gt; points out a lack of taxonomical complement to our picture. We might want to say that the former is for two taxonomically separable variants, whereas the latter is for variants that we lump together (perhaps there is a taxonomy that describes them, but we don&apos;t care in the dictionary at hand). 
> **Note**: As for the noun/adjective, noun/verb, gender or animacy, etc. differences, my assumption was that the form is the same, and we discriminate at the level of sense. That is: a single &lt;form&gt;, *no* &lt;gramGrp&gt; directly under &lt;entry&gt; (for the conversion cases, A/N, N/V), and separate senses, each with its &lt;gramGrp&gt;.An interesting question raised by this sketch is what happens if the form is identical orthographically but distinct phonetically (e.g. &quot;separate&quot;, verb vs. adjective). In such cases, we would need a parallel split inside &lt;form&gt;, and inside &lt;sense&gt;, and ideally a mechanism to relate them.

I would like, if possible, to get some consensus on what we can recommend here. I don't think we'll be able to completely rule out variety, but we should have a clear statement on what we consider "best practice" in this respect and why.

**Comment by xlhrld** [comment]
If you want to label any of the possible variants you obviously **have** to split into separate variant forms to fix the scope of e.g. `usg`:
```xml
<form type="variant">
  <pron notation="ipa">'keɹə"mɛl</pron>
  <usg type="...">...</usg>
</form>
<form type="variant">
  <pron notation="ipa">'kaɹmɫ̩</pron>
</form>
```
If `pron` is multi-valued without any explicitly mentioned further constraints (as in the initial example) I think it'll be reasonable to »maximize« the content of `entry/form` for the sake of readability and also for some restrain from interpretation. As long as the entry doesn't explicitly state the difference (e.g. by way of `usg`) between the variant forms they should not be modeled as separate variants.

So this should be perfectly fine if the dictionary puts no emphasis on distinguishing AE vs. BE in spelling and pronunciation:
```xml
<form type="lemma">
  <orth>color</orth>
  <orth>colour</orth>
  <pron notation="ipa">ˈkʌl.ɚ</pron>
  <pron notation="ipa">ˈkʌl.ə</pron>
  <pron notation="ipa">ˈkʌl.əɹ</pron>
</form>
```
Simple is better than complex. Complex is better than complicated …

**Comment by ttasovac** [comment]
This is now well-documented in the guidelines. https://dariah-eric.github.io/lexicalresources/pages/TEILex0/TEILex0.html#multiple-variants
