### ISSUE TITLE
<hom> potentially revisited

### ISSUE THREAD

**Issue by bansp** [DARIAH-ERIC/lexicalresources#161]
This is just a heads-up about an issue raised by Christian-Emil Ore at https://github.com/TEIC/TEI/issues/2273

Maybe some of his examples and use-cases may be useful for Lex0 -- they are definitely real-life ones.

**Comment by laurentromary** [comment]
I have seen this, but would really like to see an encoding proposal to make sure I understand what he wants...

**Comment by ttasovac** [comment]
I responded in the other thread. I don't see a need for any immediate changes to TEI Lex-0 so I will close this for now.
