### ISSUE TITLE
Question: Can Lex0 be used on Lexonomy?

### ISSUE THREAD

**Issue by Ob1bob** [DARIAH-ERIC/lexicalresources#162]
Hi, I'd like to know if there is a simple way to import the TEI-Lex0 schema ([TEILex0.rng](https://raw.githubusercontent.com/DARIAH-ERIC/lexicalresources/master/Schemas/TEILex0/out/TEILex0.rng)) into the [www.lexonomy.eu](http://www.lexonomy.eu/) site to build a dictionary there that is compliant with its structural specifications? Thanks

**Comment by ttasovac** [comment]
I have no idea, probably not, I think Lexonomy has its own schema editor, which you need to set up manually before starting to work on your dictionary, but you should really check about this with Lexonomy support. If there is no direct link to contact Lexonomy support, I suggest asking on their Github: https://github.com/elexis-eu/lexonomy/issues 

All best,
Toma
