### ISSUE TITLE
transitivity or valency

### ISSUE THREAD

**Issue by JessedeDoes** [DARIAH-ERIC/lexicalresources#173]
There is a separate property "transitivity" in lex0. 
We also need to encode properties like "impersonal", which are traditionally grouped under "valency".
So we would be inclined to encode intransitive "rain"
as
```
<gram type="valency">impersonal</gram>
<gram type="valency">intransitive</gram>
```

Reflexivity could also be added here.

Cf: https://en.wikipedia.org/wiki/Valency_(linguistics)

**Comment by bansp** [comment]
I find this to be an interesting didactic case, for when one wants to show students how lexicography differs from linguistics. Intuitively, for a linguist, conflating (let's call it) 'quantitative' valency with 'qualitative' valency is a bad move. (The former having to do with argument slots for a predicate, the latter with the semantics of (some of) those arguments).
BUT I can't honestly say it's an impractical lexicographic approach. If the Wikipedia list of suggested values is used:
`impersonal, intransitive, transitive, ditransitive, tritransitive`, I can see that working in a dictionary (although my first reaction to seeing that list was that it represents some kind of didactic approach dressed up as general truth).

I'm not sure how `reflexive` would work with this, but it becomes a matter of convention and of documenting that convention. (My questions would be, e.g.,  whether the same tag would be used for `He perjured himself` and `He killed himself` -- in a dictionary, maybe yes; or whether `he gave himself a smack` is an issue -- probably not, if you can stack those tags, as suggested above, and if documentation is provided).
