### ISSUE TITLE
xml:lang object language

### ISSUE THREAD

**Issue by kdepuydt** [DARIAH-ERIC/lexicalresources#174]
The use of the term object language may be perceived as confusing. Is it the language that is described in the dictionary entry or the language used in the description

**Comment by ttasovac** [comment]
This is standard ISO terminology, and we describe it in some detail here: https://dariah-eric.github.io/lexicalresources/pages/TEILex0/spec.html#TEI.language. Does that help?

**Comment by laurentromary** [comment]
I can just confirm this. Object language is differentiated from working language: the one you use to provide information about the object language.
