### ISSUE TITLE
norm is not allowed

### ISSUE THREAD

**Issue by anacastrosalgado** [DARIAH-ERIC/lexicalresources#177]
@ttasovac The ```abbr``` element is ok, but the ```norm``` attribute is not allowed.
Example:

```xml
<item>
   <abbr type="POS" norm="adposition">Prep.</abbr>
   <expan>Prepoſição</expan>
   <p>.</p>
</item>
```

**Comment by ttasovac** [comment]
It shouldn't be allowed. See https://github.com/DARIAH-ERIC/lexicalresources/issues/176#issuecomment-1417621623
