### ISSUE TITLE
hint > miscellaneous (value) in abbreviations list

### ISSUE THREAD

**Issue by anacastrosalgado** [DARIAH-ERIC/lexicalresources#178]
miscellaneous: consisting of members or elements of different kinds; of mixed composition or character (OED definition)

We will use ```miscellaneous``` to identify elements that do not have a proper classification, and it's irrelevant to classify them.
 
Example:

```xml
<item>
   <abbr type="miscellaneous">I. e.</abbr>
   <expan>iſto he</expan>
   <p>.</p>
</item>
```

**Comment by ttasovac** [comment]
This is fine, but this is not an issue for TEI Lex-0. This is something we've decided you will do with the abbreviations that don't fit into your classification of abbreviations (domain, grammar etc.)

**Comment by anacastrosalgado** [comment]
Ok. I will put this in my repository.
