### ISSUE TITLE
Version attribute on TEI

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/lexicalresources#183]
This is a placeholder from the Lexical Resources Summit. We need a mechanism to indicate the version of TEI Lex-0 that the document is encoded in. The natural place would be `@version` on `TEI` but there are constraints there on what can go in (numbers and dots) + this is reserved for the version of plain TEI. There is a history of discussions around this and an open [ticket](https://github.com/TEIC/TEI/issues/1993) on TEI-C. But this is important for us because we want a machine readable way of showing that something is TEI Lex-0.

To be discussed further.

**Comment by daliboris** [comment]
We will introduce mandatory `@type` attribute on `TEI`  element with fixed value “lex-0”.

The `@version` attribute refers to the version of TEI Lex-0 and will not be mandatory.
