### ISSUE TITLE
Add front and back to the schema

### ISSUE THREAD

**Issue by anacastrosalgado** [DARIAH-ERIC/lexicalresources#192]
I noticed that `front` and `back` elements are not allowed while encoding the Morais front matter.

**Comment by ttasovac** [comment]
Actually, `front` and `back` _are_ allowed. They are the children of `text`, i.e. they come before and after `body`. So you were either trying to put them in the wrong place, or something is not right with your xi:includes...  I will close this for now, but can help you separately to figure out what's wrong on your end...

**Comment by anacastrosalgado** [comment]
@ttasovac Do you have 5 minutes?
