### ISSUE TITLE
Two recomended values for temporal <usg> label

### ISSUE THREAD

**Issue by daliboris** [DARIAH-ERIC/lexicalresources#193]
In chapter [`8.2. Types of usage`](https://dariah-eric.github.io/lexicalresources/pages/TEILex0/TEILex0.html#index.xml-body.1_div.8_div.2) example for temporal label has `@type` value `time` (`<usg type="time"/>`) but in the following table the reguired value is `temporal`.

**Comment by anacastrosalgado** [comment]
We must change `time` >` temporal`. The https://raw.githubusercontent.com/DARIAH-ERIC/lexicalresources/feature/listBibl/Schemas/TEILex0/out/TEILex0.rng doesn't allow `temporal` value.

**Comment by daliboris** [comment]
Are you sure, @anacastrosalgado?  An example is taken from [Salgado et al. 2019b](https://dariah-eric.github.io/lexicalresources/pages/TEILex0/TEILex0.html#Salgado2019b) and you use only `<usg type="time"/>` in Morais. And [TEILex0.rng](https://raw.githubusercontent.com/DARIAH-ERIC/lexicalresources/feature/listBibl/Schemas/TEILex0/out/TEILex0.rng) allows only `time` value too.

Maybe wrong value (`temporal`) is in the table.

**Comment by anacastrosalgado** [comment]
Yes, I'm sure. We defined this value here:
[](https://zenodo.org/record/3664669#.ZE-VpXbMKHs)

temporal label
marker which identifies the use of a given lexical unit on a scale from old to new syn: diachronic marking; diachronic information; time label
E.g.: abada ant. [rhinoceros], beque ant., postilhao ant.

**Comment by ttasovac** [comment]
yes, temporal is the correct value. Fixed in the dev branch.

**Comment by anacastrosalgado** [comment]
Thanks.
