### ISSUE TITLE
Orthographic variants grouped in one entry

### ISSUE THREAD

**Issue by anacastrosalgado** [DARIAH-ERIC/lexicalresources#196]
![image](https://user-images.githubusercontent.com/45368069/235730022-c87fb931-6963-43f9-ac47-9ef7f186760e.png)

![image](https://user-images.githubusercontent.com/45368069/235731208-02e0002f-cf3c-4d0b-966d-beb6a84cccf7.png)

In the Morais dictionary, sometimes, orthographic variants are presented as separate entries, but just one of the entries has content _per se_. As I want to encode these entries as nested entries, I'm using `type="homonymicEntry"`. Is it possible to have type=`"variantEntry"`?

```xml
<entry xmlns="http://www.tei-c.org/ns/1.0" xml:id="MORAIS.1.DLP.BAGULHADO_BAGULHENTO" type="mainEntry" xml:lang="pt">
   <entry xml:id="MORAIS.1.DLP.BAGULHADO" type="homonymicEntry" xml:lang="pt">
      <!-- Morais considers the two different entries together; therefore he used the brackets; homonymic entry is not the best solution -->
      <metamark function="variantDelimiter">(</metamark>
      <form type="lemma">
         <orth>BAGULHADO</orth>
      </form>
      <metamark function="lemmaDelimiter">,</metamark>
      <gramGrp>
         <gram type="pos" norm="ADJECTIVE">adj.</gram>
      </gramGrp>
   </entry>
   <entry xml:id="MORAIS.1.DLP.BAGULHENTO" type="homonymicEntry" xml:lang="pt">
      <metamark function="variantDelimiter">(</metamark>
      <form type="lemma">
         <orth>BAGULHENTO</orth>
      </form>
      <metamark function="lemmaDelimiter">,</metamark>
      <gramGrp>
         <gram type="pos" norm="ADJECTIVE">adj.</gram>
      </gramGrp>
      <sense xml:id="MORAIS.1.DLP.BAGULHENTO.s.2">
         <def>que tem bagulho</def>
      </sense>
      <bibl type="attestation" corresp="mor.bibl.authr.titl">
         <author>B. P.</author>
      </bibl>
   </entry>
```

```xml
<entry xmlns="http://www.tei-c.org/ns/1.0" xml:id="MORAIS.1.DLP.BAHU_BAHUL" type="mainEntry" xml:lang="pt">
   <entry xml:id="MORAIS.1.DLP.BAHU" type="homonymicEntry" xml:lang="pt">
      <!-- Morais considers the two different entries together;
                                therefore he used the brackets; homonymic entry is not the best solution -->
      <metamark function="variantDelimiter">(</metamark>
      <form type="lemma">
         <orth>BAHU</orth>
      </form>
      <metamark function="lemmaDelimiter">,</metamark>
      <gramGrp>
         <gram type="pos" norm="NOUN">ſ.</gram>
         <gram type="gen">m.</gram>
      </gramGrp>
   </entry>
   <entry xml:id="MORAIS.1.DLP.BAHUL" type="homonymicEntry" xml:lang="pt">
      <metamark function="variantDelimiter">(</metamark>
      <form type="lemma">
         <orth>BAHUL</orth>
      </form>
      <metamark function="lemmaDelimiter">,</metamark>
      <gramGrp>
         <gram type="pos" norm="NOUN">ſ.</gram>
         <gram type="gen">m.</gram>
      </gramGrp>
      <sense xml:id="MORAIS.1.DLP.BAHUL.s.2">
         <def>cofre encoirado , de tampa como volta d’abobada , convexa</def>
      </sense>
      <pc>:</pc>
      <usg type="frequency"><hi>bahu</hi> he mais uſado.</usg>
   </entry>
</entry>
```

@daliboris @ttasovac @laurentromary

**Comment by bansp** [comment]
Would you kindly check if the paper by Bański, Bowers, and Erjavec mentions that? Can't do that myself right now, so I'm just dropping the link:

https://ids-pub.bsz-bw.de/frontdoor/deliver/index/docId/6427/file/Banski_Bowers_Erjavec_TEI_Lex0_2017.pdf

**Comment by ttasovac** [comment]
@anacastrosalgado the suggested values for `@type` on `entry` belong to a so-called semi-open list, i.e. they are not the only values allowed, and you can add your own types without invalidating your TEI Lex-0. So there is no reason why _you_ couldn't use `variantEntry` in your project —  we wouldn't have to change anything in TEI Lex-0 for it.

Here's a similar example:

![](https://i.imgur.com/iocfvQW.jpg)

There is, indeed, nothing homonymic here: we have two separate forms (even with different POS) that are, in the case of a Serbian dictionary, defined together. And the examples in this dictionary refer to both variants. 

The question is: do we  really need two entries in such cases  —  or just one main entry, with two variant forms.  In the Serbian example above, I have no doubt that this is one entry with two variant forms. In your case, I would probably argue the same. Whether they are "autonomous entries" or not is really up for debate. 

So my initial reaction is that we probably don't need `variantEntry` as an explicit recommendation in TEI Lex-0, but let's talk about it on Wednesday in our first jour fixe! :)

**Comment by laurentromary** [comment]
I am on Toma's side and would argue for variant forms (coupled with their respective grammatical constraints).

**Comment by ttasovac** [comment]
@anacastrosalgado I will close this for now — feel free to bring it up during our meeting on Wednesday if you want more discussion around it

**Comment by anacastrosalgado** [comment]
@ttasovac and @laurentromary I hadn't actually realized that the values ​​weren't closed. Cool.
Thanks for the example from the Serbian dictionary. There is something different in the Portuguese dictionary.
For **bahu** and **bahul**, I have no doubt that this is one entry with two variant forms. I can encode them as variant forms coupled with their respective grammatical constraints. However, for **bagulhado** and **bagulhento**, I don't consider them orthographic variants. They are two different lexical units, synonyms it is true, but they are not exactly variants (bagulho + -ado and bagulho + -ento). I would classify them as synonyms, but never as variants. (We can discuss this tomorrow).

**Comment by laurentromary** [comment]
I would suggest to make sure there are strong surface markers to depart from the general form variant perspective. In particular, I think is there are exceptions based on precise linguistic analysis, this may be a problem if these are to be learned by processes such as Grobid.
