### ISSUE TITLE
Discrepancy between proposed and used value for temporal label

### ISSUE THREAD

**Issue by daliboris** [DARIAH-ERIC/lexicalresources#204]
In the Guidleines are examples of the value for temporal label (i.e. _marker which identifies the use of a given lexical unit on a scale from old to new. Syn: diachronic marking; diachronic information; time label_) .

In examples:

- `<usg type="time">Vor 1996 Rechtschreibung Reform</usg>`
- `<usg type="time" expand="originally">orig</usg>`

In chapter [**8.2. Types of usage**](https://dariah-eric.github.io/lexicalresources/pages/TEILex0/TEILex0.html#index.xml-body.1_div.8_div.2):

- `<usg type="time"/>`

In the table:

TEI P5 (suggested types): **time**
TEI Lex-0 (required types): **temporal**

In the [`<usg>`definigtion](https://dariah-eric.github.io/lexicalresources/pages/TEILex0/spec.html#TEI.usg) 
legal values:  **time**: _marker which identifies the use of a given lexical unit on a scale from old to new_

There is discrepancy between proposed value for Lex-0 (**temporal**) in the table and used value (**time**).

**Comment by ttasovac** [comment]
resolved in #213

**Comment by daliboris** [comment]
In the documentation (version 0.9.3) the value `time` (instead of `temporal`) is still in the example under the **temporal label**:

```xml
<usg type="time"/>
```
![vivaldi_2024-04-07T21-00-34](https://github.com/DARIAH-ERIC/lexicalresources/assets/8056045/a76e2f8c-1312-435d-93bc-cc2bd13f6dc1)
