### ISSUE TITLE
Still the header

### ISSUE THREAD

**Issue by anacastrosalgado** [DARIAH-ERIC/lexicalresources#205]
@ttasovac I need to include the collaboration of @daliboris in the header. In his case, he is a freelancer with no affiliation. I'm using `state` (not allowed).
https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-editor.html

```xml
<editor role="Researcher">
    <persName>
        <forename>Toma</forename>
        <surname>Tasovac</surname>
    </persName>
    <affiliation n="1">DARIAH-EU, Digital Research Infrastructure for the Arts and
        Humanities</affiliation>
    <affiliation n="2">BCDH, Belgrade Center for Digital Humanities</affiliation>
</editor>
<editor role="Developer">
    <persName>
        <forename>Boris</forename>
        <surname>Lehečka</surname>
    </persName>
    <state>Freelancer developer</state>
</editor>
```

**Comment by ttasovac** [comment]
I'd rather not introduce an additional element for that. You can either use affiliation and put Freelance developer there, or simply have no affiliation...
