### ISSUE TITLE
xr/@subtype?

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/lexicalresources#22]
We say:

> `@type` is a mandatory attribute on xr for a lexical reference. Its default value is "lexical" and can be superseded (or complemented by means of `@subtype`).

Now, subtype is not allowed on xr in TEI itself and we don't have any examples of what subtype would be used for here.

I would like to get rid of this, but need a second opinion and/or good examples for this.

**Comment by ttasovac** [comment]
(Laurent and I say) we don't see a specific need for subtype and we haven't seen any examples of it.

**Comment by laurentromary** [comment]
see https://github.com/TEIC/TEI/issues/1810

**Comment by ttasovac** [comment]
we may revisit this if see some examples, but for the time being, i'm closing this.

**Comment by laurentromary** [comment]
Breaking news: https://github.com/TEIC/TEI/issues/1810#issuecomment-522595850 has received consent from TEI council.
