### ISSUE TITLE
xpath/xpointer expressions in ref/@target

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/lexicalresources#23]
We say that ref/@target could have the following values:

- `#` + `xml:id`: reference to element by `xml:id` inside current document
- URI reference
- xpath/xpointer expressions, using TEI xpointer schemes (http://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SATS)
- #null: there is no concrete reference

I would like to propose that we get rid of xpath/xpointer expressions. I think TEI Lex-0 doesn't have to cover everything that TEI does. I need a second opinion and/or good examples/arguments for why we would want to point to things this way.

**Comment by ttasovac** [comment]
Ok, (Laurent and I discusing) We are not going to do null, but rather allow no attribute target.

The text should say: we use URI reference as per TEI, but more specifically we impose that intradictionary references are based on explicit xml:id references.

**Comment by ttasovac** [comment]
Dear @laurentromary,

I changed the description as we discussed the other day. However, this still feels incomplete to me. I think we should:

- further constrain URIs to allow only `http` or `https` prefixes. We shouldn't allow URIs that start with `ftp`, `mailto` or `file` for instance.
- enforce that local references (to the same dictionary) are in the shape of #+xml:id (and, perhaps, offer a schematron rule for checking all links —  we use those regulary) 
- we need a way to enforce that no xpointers are used (i.e. `#xpath(`), `#range()` etc. should not be allowed. 

What do you think? 



Also, if we say that TEI pointers should _not_ be used for internal references (which we now _do_ say, and I think it's important, because all those xpath expressions can become very complex, and we want the pointers to be as straight-forward as possible) is Schematron the only way to "disable" them?

**Comment by laurentromary** [comment]
I would really not hack the anyURI type in our context since the syntax covers all our needs  (see [https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Examples_2]) and we mainly need to be explicit in our text about what we recommend.

**Comment by ttasovac** [comment]
Ok. I was thinking it would be more useful to restrict for the sake of post-processing etc., but we shouldn't prevent people from using TEI Lex-0 also in their own work (not just as a baseline encoding for comparison) so in that sense it wouldn't make sense to impose additional restrictions.
