### ISSUE TITLE
xr in def, and more generally: rethinking the content model of def

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/lexicalresources#24]
We had this example:

```xml
<entry>
  <form type="lemma">
    <orth>dog</orth>
  </form>
  <sense>
    <def>Four-footed barking over-enthusiastic <xr type="hyperonym">
      <ref type="entry">animal</ref></xr>, best friend of
      man; is a <xr type="hyperonym">
      <ref type="entry">canine</ref></xr>
    </def>
  </sense>
</entry>
```
I understand why it would be useful to encode hyperonyms in definitions. In fact, I think this is something that we _should_ enable —  I always wanted to do something like that in our dictionaries, but I never got around to doing it.

The problem is that you can't have an `xr` in `def` in vanilla TEI. 

I have removed this example from the current TEI Lex-0 because we need to agree on changing the content model of `def` (which seems absurdly permissive)  —  and discuss whether we should pursue some of the changes in TEI itself. I also think we'll need more time for this, hence it would be unrealistic to aim for 0.7.0

**Comment by xlhrld** [comment]
+1 for eventually streamlining the content model of `def` – but that requires quite a bit of discussion, I agree.

**Comment by ttasovac** [comment]
We are making <xr> member of emphLike
