### ISSUE TITLE
Add all authors' names to the TEI header

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/lexicalresources#27]

**Comment by kdepuydt** [comment]
What is meant here?

**Comment by ttasovac** [comment]
Done, to the best of my knowledge and as far as my senility allows me to remember anything. 

You can see the list of contributors also here: https://dariah-eric.github.io/lexicalresources/pages/TEILex0/TEILex0.html#index.xml-body.1_div.1_div.2_div.3 

If I've missed anybody, we'll add them later, of course.
