### ISSUE TITLE
Add <lang> to model.entryPart in TEI-Lex0 ODD 

### ISSUE THREAD

**Issue by iljackb** [DARIAH-ERIC/lexicalresources#29]
<lang> needs to be allowed inside of etymons, cognate and other forms cited in the etymology section
e.g.
```
               <cit type="cognate">
                  <lang>dän.</lang>
                  <form>
                     <orth xml:lang="da">indgang</orth>
                  </form>
               </cit>
```
Can you add this to the ODD?

I can propose to make this official on the TEI-C git also..

**Comment by ttasovac** [comment]
Wait, I don't quite understand your example. Lang refers to Danish, but the form is German. What does that actually mean?

**Comment by iljackb** [comment]
oops lang tag is wrong sorry

**Comment by ttasovac** [comment]
and you don't want to put lang inside form?

**Comment by iljackb** [comment]
nope, because it's not part of the form, also there may be cases where there are multiple forms that are listed following a language; e.g.
```
               <cit type="etymon">
                  <lang>mhd.</lang>
                  <form type="variant">
                     <orth xml:lang="gmh">vreten</orth>
                  </form>
                  <form type="variant">
                     <orth xml:lang="gmh">vretten</orth>
                  </form>
                  <form type="variant">
                     <orth xml:lang="gmh">vraten</orth>
                  </form>
                  <def>entzünden; wundreiben; herumziehen; quälen; plagen</def>    
               </cit>
```

**Comment by ttasovac** [comment]
Right... now it's all coming back.

I'll leave this for @laurentromary for after 6pm... :) 

Jack, I'll write to you separately about the whole etym section and how to move it to our TEI Lex-0 documentation... but it will probably have to wait until tomorrow.
