### ISSUE TITLE
Modify TEI Lex0-ODD to allow both <bibl> & <ref> to occur as children of <cit>, <etym> & <entry>

### ISSUE THREAD

**Issue by iljackb** [DARIAH-ERIC/lexicalresources#33]
In the etymology section common places for bibliographic references are:

- as a child of `<etym>` _or_
- w/in etymons, cognates (i.e. `<cit>`)

In the etymology section these can be `<bibl>` or `<ref type="bibl">`.

We have `<ref type="bibl">` (with a pointer to the source in `@target`) as the alternative to `<bibl>` where there is a predeclared bibliography that can be referenced.

In the current draft of the ODD these are not allowed (though I'm sure we've discussed this).

As for the changes, I think that making `<bibl>` a member of `model.entryPart` is one of the things needed, I'm not sure about what to do with `<ref>`'s content model...

**Bonus:**
Even though it is beyond the etymology section, it would be good to allow `<bibl>` to occur as a child of `<entry>` (which is strangely not allowed). I also noticed that `<ref>` isn't allowed as a child of `<entry>`, (it is in the general TEI though). Since `<ref type="bibl">` can occur wherever a `<bibl>` might occur, it would be good to make sure they are both allowed in the same places.

I would support and take the lead on pushing to get all of these added to the general TEI

**Comment by laurentromary** [comment]
I agree with the move: to be at the appraise level of TEI style modeling, it should be based on putting model.biblLike (important to get structured bibliographic description as well as manuscript) and model.ptrLike at the right places.
OK, now looking at the situation so far, things seem to be pretty set already, aren't they?:
- `<cit>` seems to be all fine already: have we done something in the TEI lex specification that blocks one or the other element?
- `<etym>` seems to be fine as well
- `model.biblLike` should be added to `<entry>` (ref is already there)

**Comment by ttasovac** [comment]
@iljackb @kdepuydt Laurent and I are implementing bibl within entry. However, we would need acutal use examples for this, both for TEI Lex-0 and perhaps even for a possible ticket for the TEI Council. Could you guys give us good use cases?

**Comment by WGBS2** [comment]
Hi

We have an unfinished copy of our letter C encoding from the 1701 Dictionnaire universel on github at wgbs2/Basnage. That will show how we use bibl fir citations and author references.

We are not totally TEI lex0 friendly as some decisions do not fit this type of dictionary and I am also working on a deeper encoding.

Hope this is helpful and feel free to criticize as we still need to talk all this through. I miss ENEL and won’t be in Graz as I must be in Valencia at the same time.

Best

Geoffrey 

Envoyé de mon iPhone

**Comment by kdepuydt** [comment]
Several articles in the Dictionary of Old Dutch end with bibliographical references ("Literatuur"). Example: http://gtb.ivdnt.org/iWDB/search?actie=article&wdb=ONW&id=ID2424&lemmodern=god&domein=0&conc=true
![afbeelding](https://user-images.githubusercontent.com/14764143/59062844-0ff2d800-88a7-11e9-933e-ca06365ea838.png)

**Comment by laurentromary** [comment]
Thanks Kathrien. Would it be possible for you to file a feature request on the TEI GitHub so that we have this globally in the guidelines?

**Comment by iljackb** [comment]
I don't have any examples of this as in all of my endeavors the bibl info
is specific to only a portion of the entry (eg. etym, form, etc). But as is
obvious, the use case is if you take an entry from a given bibliographic
source then the <bibl> would go on the level of entry.

Best
Jack

**Comment by ttasovac** [comment]
I created a ticket for the TEI Council on this —  see link above this post. Please consider giving it a 👍.
