### ISSUE TITLE
Reinstate att.fragmentable to Lex0 ODD

### ISSUE THREAD

**Issue by iljackb** [DARIAH-ERIC/lexicalresources#35]
In the Lex0 ODD, att.fragmentable is for some reason deleted:
`<classSpec ident="att.fragmentable" mode="delete" type="atts"/>`

We need these attributes for `<seg @part>` which we use to encode non-contiguous text in the etymology section.

In conclusion please reinstate att.fragmentable at least on <seg> so we can have the aforementioned feature.

```
            <etym>
               <seg type="desc" part="I">seit dem</seg>
               <usg type="date">
                  <date>18.  Jh.</date>
               </usg>
               <seg type="desc" part="M">belegt, auf</seg>
               <cit type="etymon">
                  <form>
                     <orth xml:lang="de">fickfacken</orth>
                  </form>
                  <sense>
                     <def>'hin- und herlaufen'</def>
                  </sense>
               </cit>
               <seg type="desc" part="F">zurückgeführt</seg>;       
               <seg type="desc" part="I">evtl. auch auf </seg>
               <cit type="etymon">
                  <lang>fnhd.</lang>
                  <form>
                     <orth xml:lang="de-x-FNHD">fatzen</orth>
                  </form>
                  <!-- frühneuhochdeutsch -->
                  <sense>
                     <def>'spotten, zum Narren halten'</def>
                  </sense>
               </cit>
               <seg type="desc" part="F">zurückführbar</seg>
               <bibl>(vgl. Pfeifer 2014: 329)</bibl>
            </etym>
```

**Comment by laurentromary** [comment]
Good argument. Could you give an example that I could put in the spec when I make the change? (Unless Toma would shout at this stage :-})

**Comment by iljackb** [comment]
updated

**Comment by laurentromary** [comment]
What have you updated?

**Comment by iljackb** [comment]
> What have you updated?

I added the example you requested in the request text! (☝︎⬆︎⇧)

**Comment by laurentromary** [comment]
Did you not forget to put it as `code`? I cannot see it ...

**Comment by iljackb** [comment]
<img width="750" alt="screen shot 2018-10-30 at 4 45 24 pm" src="https://user-images.githubusercontent.com/7408924/47730828-43132000-dc63-11e8-9328-2c31817d4076.png">

**Comment by laurentromary** [comment]
got it :-}
