### ISSUE TITLE
Strategy for milestones such as page numbers, columns etc. 

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/lexicalresources#4]
Somebody suggested this in GoogleDoc. I'm not sure we really need page breaks and such, but I am here influenced by years of _not caring_ about the typo-topographical aspects of legacy dictionaries. I would like to know what people think about this: should TEI Lex-0 care about page breaks, columns and such or not?

**Comment by xlhrld** [comment]
I don't see a real lexicographical relevance for them either. But then again, at least these things don't hurt so long as they are milestone-like elements (`pb`, `cb`, `lb` and such). In principle, they allow for the reconstruction of the exact recording of typographical alignment on the page. Whoever doesn't need this, can easily strip it from the TEI version of a text.

If the consensus should be to allow things like `<lb>` we would also need a recommendation as to how to mark-up words that appear split across two line with an `<lb>` in between the word fragments.

All in all I'd say no, we don't need this. Maybe these types of elements could rather be something for a (hypothetical) TEI Lex-1 guideline?

**Comment by ttasovac** [comment]
Personally, I'd rather not have these, but if we get a strong requests for this, I would include it in a later milestone. So let's see if we get any more feedback.

**Comment by JessedeDoes** [comment]
We do not see why milestones should be removed. They are one way of collating the file with the book. Of course one could turn them into cross references, but that would only confuse the issue

**Comment by ttasovac** [comment]
Closing because we'll take this up in #184
