### ISSUE TITLE
multiword expressions once and for all 

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/lexicalresources#44]
This is just a reminder, we've had numerous discussions, but we need to finalize this and decide once for all.

As per #43, we can have `<entry>` within `<sense>`. So we can now have the artist formerly known as `<re>` appear not just at the entry level, but within senses too.  

In general, we want to use these nested `<entry>` elements for multiword expressions.  I think also probably for proverbs, sayings etc... 

But we had an interesting Portuguese example today where <b>pena<sup>+</sup> capital</b> (capital punishment) is a MWE, and the plus superscript indicates that pena is a cross-reference to the entry pena...

To be continued...

**Comment by ttasovac** [comment]
Possibly related to #12

**Comment by kdepuydt** [comment]
Technical problem with pena+ capital is xr within form or orth? we had something similar in VMNW. Should be allowed; other ref types of this (oRef etc) are allowed, why not xr

In general: as a lexicographer, who wants to encode a dictionary, I would like the structure to reflect the decisions made by the lexicographer, so encode as entry (related entry) what the lexicographer treated as entry. So no entry for proverbs, nor for collocations or idioms...

**Comment by anacastrosalgado** [comment]
pena+ capital
<entry xml:id="DACL.CAPITAL:1" xml:lang="pt">
<form type="lemma">
<orth>capital</orth>
<lbl>:1</lbl>
<pron>kɐpitˈał</pron>
</form>
<gramGrp>
<pos>adj.</pos>
<gen>m. e f.</gen>
</gramGrp>
<sense xml:id="DACL.CAPITAL.6" n="1">
<usg type="hint">P. us.</usg>
<def>Que é relativo a cabeça.</def>
</sense>
<sense xml:id="DACL.CAPITAL.8" n="2">
<def> Que está relacionado com a condenação à morte.</def>
<cit type="example"><quote>Os jurados pronunciaram-se a favor de uma sentença capital para o criminoso.</quote></cit>
<entry xml:id="DACL.EXECUÇÃO.CAPITAL" xml:lang="pt">
<form><orth>execução capital</orth></form>
</entry>
<entry xml:id="DACL.PECADO.CAPITAL" xml:lang="pt">
<form><orth>pecado capital</orth></form>
</entry>
<entry xml:id="DACL.OU.EXECUÇÃO" xml:lang="pt">
<form><orth>ou execução</orth></form>
</entry>
<entry xml:id="DACL.PENA.CAPITAL" xml:lang="pt">
<form><orth>pena capital</orth></form>
</entry>
</sense>
<sense xml:id="DACL.CAPITAL.10" n="3" xml:lang="pt">
<def> Que é de primeira ou grande importância.</def>
<xr type="synonymy"><ref type="sense">essencial</ref></xr>
<xr type="synonymy"><ref type="sense">fundamental</ref></xr>
<xr type="synonymy"><ref type="sense">principal</ref></xr>
<cit type="example"><quote>Preocupação capital. Assunto de interesse capital.</quote>
</cit>
</sense>
<entry xml:id="DACL.LETRA.CAPITAL.11" xml:lang="pt">
<form><orth>letra capital</orth></form>
</entry>
<entry xml:id="DACL.PECADO.CAPITAL.12" xml:lang="pt">
<form><orth>pecado capital</orth></form>
</entry>
<etym>
<seg type="desc">Do</seg>
<cit type="etymon"> <lang>la.</lang> <form><orth xml:lang="la">capitālis</orth></form>
</cit>
</etym>
</entry>
<entry xml:id="DACL.CAPITAL:2" xml:lang="pt">
<form type="lemma">
<orth>capital</orth>
<lbl>:2</lbl>
<pron>kɐpitˈał</pron>
</form>
<gramGrp>
 <pos>n.</pos>
 <gen>f.</gen>
 </gramGrp>
 <sense xml:id="DACL.CAPITAL.6" n="1">
 <def>Cidade onde está situada a sede administrativa de um país, província, região... </def>
 <cit type="example">
 <quote>Duarte, um mês depois, era preso, interrogado, e remetido para a capital, onde a identidade da pessoa foi de muitos reconhecida.</quote>
 <bibl><author>CAMILO</author>, <title>As Três Irmãs</title>, <citedRange>151</citedRange></bibl>
</cit>
<entry xml:id="DACL.CAPITAL.8." xml:lang="pt">
<form><orth>+ de distrito.</orth></form>
</entry>
</sense>
<sense xml:id="DACL.CAPITAL.9" n="2">
<def>Cidade que constitui o centro de uma actividade.</def>
<cit type="example">
<quote>Diz-se que Paços de Ferreira é a capital do móvel.</quote>
</cit>
</sense>
<sense xml:id="DACL.CAPITAL.10" n="3">
<def>Letra maiúscula; letra maiúscula que inicia um capítulo.</def>
</sense>
<etym>
<seg type="desc">Do</seg>
<cit type="etymon"> <lang>la.</lang> <form><orth xml:lang="la">capitālis</orth></form>
</cit>
</etym>
</entry>

**Comment by anacastrosalgado** [comment]
pena+ capital

<entry xml:id="DACL.CAPITAL:1" xml:lang="pt">
<form type="lemma">
<orth>capital</orth>
<lbl>:1</lbl>
<pron>kɐpitˈał</pron>
</form>
<gramGrp>
<pos>adj.</pos>
<gen>m. e f.</gen>
</gramGrp>
<sense xml:id="DACL.CAPITAL.6" n="1">
<usg type="hint">P. us.</usg>
<def>Que é relativo a cabeça.</def>
</sense>
<sense xml:id="DACL.CAPITAL.8" n="2">
<def> Que está relacionado com a condenação à morte.</def>
<cit type="example"><quote>Os jurados pronunciaram-se a favor de uma sentença capital para o criminoso.</quote></cit>
<entry xml:id="DACL.EXECUÇÃO.CAPITAL" xml:lang="pt">
<form><orth>execução capital</orth></form>
</entry>
<entry xml:id="DACL.PECADO.CAPITAL" xml:lang="pt">
<form><orth>pecado capital</orth></form>
</entry>
<entry xml:id="DACL.OU.EXECUÇÃO" xml:lang="pt">
<form><orth>ou execução</orth></form>
</entry>
<entry xml:id="DACL.PENA.CAPITAL" xml:lang="pt">
<form><orth>pena capital</orth></form>
</entry>
</sense>
<sense xml:id="DACL.CAPITAL.10" n="3" xml:lang="pt">
<def> Que é de primeira ou grande importância.</def>
<xr type="synonymy"><ref type="sense">essencial</ref></xr>
<xr type="synonymy"><ref type="sense">fundamental</ref></xr>
<xr type="synonymy"><ref type="sense">principal</ref></xr>
<cit type="example"><quote>Preocupação capital. Assunto de interesse capital.</quote>
</cit>
</sense>
<entry xml:id="DACL.LETRA.CAPITAL.11" xml:lang="pt">
<form><orth>letra capital</orth></form>
</entry>
<entry xml:id="DACL.PECADO.CAPITAL.12" xml:lang="pt">
<form><orth>pecado capital</orth></form>
</entry>
<etym>
<seg type="desc">Do</seg>
<cit type="etymon"> <lang>la.</lang> <form><orth xml:lang="la">capitālis</orth></form>
</cit>
</etym>
</entry>
<entry xml:id="DACL.CAPITAL:2" xml:lang="pt">
<form type="lemma">
<orth>capital</orth>
<lbl>:2</lbl>
<pron>kɐpitˈał</pron>
</form>
<gramGrp>
 <pos>n.</pos>
 <gen>f.</gen>
 </gramGrp>
 <sense xml:id="DACL.CAPITAL.6" n="1">
 <def>Cidade onde está situada a sede administrativa de um país, província, região... </def>
 <cit type="example">
 <quote>Duarte, um mês depois, era preso, interrogado, e remetido para a capital, onde a identidade da pessoa foi de muitos reconhecida.</quote>
 <bibl><author>CAMILO</author>, <title>As Três Irmãs</title>, <citedRange>151</citedRange></bibl>
</cit>
<entry xml:id="DACL.CAPITAL.8." xml:lang="pt">
<form><orth>+ de distrito.</orth></form>
</entry>
</sense>
<sense xml:id="DACL.CAPITAL.9" n="2">
<def>Cidade que constitui o centro de uma actividade.</def>
<cit type="example">
<quote>Diz-se que Paços de Ferreira é a capital do móvel.</quote>
</cit>
</sense>
<sense xml:id="DACL.CAPITAL.10" n="3">
<def>Letra maiúscula; letra maiúscula que inicia um capítulo.</def>
</sense>
<etym>
<seg type="desc">Do</seg>
<cit type="etymon"> <lang>la.</lang> <form><orth xml:lang="la">capitālis</orth></form>
</cit>
</etym>
</entry>

**Comment by anacastrosalgado** [comment]
<entry xml:id="DACL.CAPITAL:1" xml:lang="pt">
<form type="lemma">
<orth>capital</orth>
<lbl>:1</lbl>
<pron>kɐpitˈał</pron>
</form>
<gramGrp>
<pos>adj.</pos>
<gen>m. e f.</gen>
</gramGrp>
<sense xml:id="DACL.CAPITAL.6" n="1">
<usg type="hint">P. us.</usg>
<def>Que é relativo a cabeça.</def>
</sense>
<sense xml:id="DACL.CAPITAL.8" n="2">
<def> Que está relacionado com a condenação à morte.</def>
<cit type="example"><quote>Os jurados pronunciaram-se a favor de uma sentença capital para o criminoso.</quote></cit>
<entry xml:id="DACL.EXECUÇÃO.CAPITAL" xml:lang="pt">
<form><orth>execução capital</orth></form>
</entry>
<entry xml:id="DACL.PECADO.CAPITAL" xml:lang="pt">
<form><orth>pecado capital</orth></form>
</entry>
<entry xml:id="DACL.OU.EXECUÇÃO" xml:lang="pt">
<form><orth>ou execução</orth></form>
</entry>
<entry xml:id="DACL.PENA.CAPITAL" xml:lang="pt">
<form><orth>pena capital</orth></form>
</entry>
</sense>
<sense xml:id="DACL.CAPITAL.10" n="3" xml:lang="pt">
<def> Que é de primeira ou grande importância.</def>
<xr type="synonymy"><ref type="sense">essencial</ref></xr>
<xr type="synonymy"><ref type="sense">fundamental</ref></xr>
<xr type="synonymy"><ref type="sense">principal</ref></xr>
<cit type="example"><quote>Preocupação capital. Assunto de interesse capital.</quote>
</cit>
</sense>
<entry xml:id="DACL.LETRA.CAPITAL.11" xml:lang="pt">
<form><orth>letra capital</orth></form>
</entry>
<entry xml:id="DACL.PECADO.CAPITAL.12" xml:lang="pt">
<form><orth>pecado capital</orth></form>
</entry>
<etym>
<seg type="desc">Do</seg>
<cit type="etymon"> <lang>la.</lang> <form><orth xml:lang="la">capitālis</orth></form>
</cit>
</etym>
</entry>
<entry xml:id="DACL.CAPITAL:2" xml:lang="pt">
<form type="lemma">
<orth>capital</orth>
<lbl>:2</lbl>
<pron>kɐpitˈał</pron>
</form>
<gramGrp>
 <pos>n.</pos>
 <gen>f.</gen>
 </gramGrp>
 <sense xml:id="DACL.CAPITAL.6" n="1">
 <def>Cidade onde está situada a sede administrativa de um país, província, região... </def>
 <cit type="example">
 <quote>Duarte, um mês depois, era preso, interrogado, e remetido para a capital, onde a identidade da pessoa foi de muitos reconhecida.</quote>
 <bibl><author>CAMILO</author>, <title>As Três Irmãs</title>, <citedRange>151</citedRange></bibl>
</cit>
<entry xml:id="DACL.CAPITAL.8." xml:lang="pt">
<form><orth>+ de distrito.</orth></form>
</entry>
</sense>
<sense xml:id="DACL.CAPITAL.9" n="2">
<def>Cidade que constitui o centro de uma actividade.</def>
<cit type="example">
<quote>Diz-se que Paços de Ferreira é a capital do móvel.</quote>
</cit>
</sense>
<sense xml:id="DACL.CAPITAL.10" n="3">
<def>Letra maiúscula; letra maiúscula que inicia um capítulo.</def>
</sense>
<etym>
<seg type="desc">Do</seg>
<cit type="etymon"> <lang>la.</lang> <form><orth xml:lang="la">capitālis</orth></form>
</cit>
</etym>
</entry>
