### ISSUE TITLE
Making +some+ dictionary elements members of  att.datable.w3c 

### ISSUE THREAD

**Issue by laurentromary** [DARIAH-ERIC/lexicalresources#45]
There are cases in the Academy of Sciences Portuguese Dictionary when forms are actually dated (cf. below). This makes me think we should probably be able to date  `<pron>` or `<orth>` and possibly other dictionary components.

`  <entry xml:id="DACL.ACTUALIZADO" xml:lang="pt">
               <form type="lemma">
                  <orth>actualizado</orth>
                  <orth notBefore= "1990">atualizado</orth>
                  <usg type="time">Acordo Ortográfico de 1990</usg>
                  
                  <pron>ɐtwɐlizˈadu, -ɐ</pron>
               </form>
               <gramGrp>
                  <pos>adj.</pos>
               </gramGrp>
           </entry>`

**Comment by laurentromary** [comment]
Another version with a `<usg>`:  `<entry xml:id="DACL.ACTUALIZADO" xml:lang="pt">
               <form type="lemma">
                  <orth xml:lang="pt-PT">actualizado</orth>
                  <form type="inflected">
                     <orth extent="suff">-a</orth>
                  </form>
                  <orth notBefore= "1990">atualizado</orth>
                  <usg type="time">Acordo Ortográfico de 1990</usg>         `

**Comment by kdepuydt** [comment]
Why do we not put this information in usage. We could also add information on regional distribution for instance, register etc. For us this is comparable.
