### ISSUE TITLE
do we want term? or name?

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/lexicalresources#46]
In many dictionaries, definitions or translations (often for plants and animals and that kind of stuff) will have a Latin name or classification attached to it...

I would probably call this <term>...

Note to self: ask Ana to send you Portuguese examples. 

To be discussed...

**Comment by laurentromary** [comment]
Ana provided more examples:
CANICHE
English: poodle
French: caniche
`<def>Raça de cães de água <mentioned author="Linn">Canis familiaris aquaticus</mentioned>, cujo pêlo é muito encaracolado. </def>`
Linn = Linnaean taxonomy, the system for classifying living things
 
MARMOTA
English: marmot
French: marmotte
`<def>Animal quadrúpede e roedor <mentioned author="Linn">A. marmota</mentioned>, sociável e herbívoro, que vive em tocas nas regiões setentrionais e hiberna vários meses. </def>`
 
Cf. Genus Marmota, family Sciuridae: several species
[https://en.oxforddictionaries.com/definition/marmot]
 
COLIBRI
English: hummingbird
French: colibri
`<def>Designação vulgar de várias aves da família dos troquilídeos <mentioned author="Linn">Trochilus</mentioned>, de tamanho reduzido, plumagem de cores vivas e brilhantes, voo muito veloz, frequentes na América tropical, também conhecidas por <xr>beija-flor</xr>, <xr>chupa-flor</xr>, </def>`

**Comment by kdepuydt** [comment]
term or name (for latin names of animals etc) Opt for term!
	`<term>` contains a single-word, multi-word, or symbolic designation which is regarded as a technical term
	`<name>` (name, proper noun) contains a proper noun or noun phrase.

**Comment by laurentromary** [comment]
Toma and I agree that `<term>` is a good thing to have.
