### ISSUE TITLE
xr bug in schema

### ISSUE THREAD

**Issue by TomazErjavec** [DARIAH-ERIC/lexicalresources#51]
The schema seems to have an error in the defintion of  `<xr>`, which currently doesn't allow plain text, i.e. it is missing `<textNode/>` in `<content>`.

**Comment by laurentromary** [comment]
This is intended. The idea is to have `<lbl>` mourn the text you would have.

**Comment by TomazErjavec** [comment]
> The idea is to have `<lbl>` mourn the text you would have.

OK, thanks, so no free text in `<xr>`. But if by "mourn" you mean "contain", then `<lbl>` is a strange choice, esp. as the docu rather gives `<ref>` to contain the text. So, I will go with that, and close the issue.
