### ISSUE TITLE
Highlighted text?

### ISSUE THREAD

**Issue by TomazErjavec** [DARIAH-ERIC/lexicalresources#53]
This is might be a conscious decision, rather than a bug, but I ask to make sure: in our dictionary we have (inside an example) CO2, which (if we are to preserve the original) should be marked up as something like `CO<hi rend="subscript">2</hi>`.
However, I now find that `<hi>` is not allowed in Lex0, and even if added, `@rend` has been explicitly removed.

So, does this mean that only plain text is allowed in e.g. examples, no italic, bold, super or subscripts? This seems rather harsh and I'm not sure what the advantage is - applications that don't know what to do with `<hi>` could simply ignore it.

**Comment by laurentromary** [comment]
The initial phase of ODD development has been of a drastic cut down of available element. Not sure I have a religion on your question. I would tend to agree with you. Let us see what @ttasovac thinks.

**Comment by ttasovac** [comment]
This was not intentional. We'll bring it back. @laurentromary perhaps we can do this quickly today during our call.

**Comment by laurentromary** [comment]
This is now implemented (not compiled).
