### ISSUE TITLE
Provide encoding proposal for cantor, a n. m., f.

### ISSUE THREAD

**Issue by laurentromary** [DARIAH-ERIC/lexicalresources#55]
Following an example from Ana Salgado. My suggestion would be to have two `<form type="inflected">` in conjunction to one lemma with cantor.

**Comment by laurentromary** [comment]
Following a discussion with Toma, we have the following thoughts:

- as a lexical-view (preferred):

` <entry>
            
            <form type="lemma">
               <orth>cantor</orth>
               <gramGrp>
                  <pos>n</pos>
               </gramGrp>
            </form>
            <form type="inflected">
               <orth>cantor</orth>
               <gramGrp>
                  <gen>m</gen>
               </gramGrp>
            </form>
            <form type="inflected">
               <orth>cantora</orth>
               <gramGrp>
                  <gen>f</gen>
               </gramGrp>
            </form>
         </entry>
`

- as an editorial view (version 1)

` <entry>
            <form type="lemma">
               <orth>cantor,a</orth>
               <gramGrp>
                  <pos>n.</pos>
                  <gen>m.</gen>
                  <pc>,</pc>
                  <gen>f.</gen>
               </gramGrp>
            </form>
         </entry>`

- version 2

`      
         <entry>
            <form type="lemma">
               <orth>cantor</orth>
               <pc>,</pc>
               <form type="ending">
                  <orth>a</orth>
               </form>
               <gramGrp>
                  <pos>n.</pos>
                  <gen>m.</gen>
                  <pc>,</pc>
                  <gen>f.</gen>
               </gramGrp>
            </form>
         </entry>
         `

**Comment by ambs** [comment]
Hopefully we should find one single way to encode things (semantically, never visually).
Adding gramGrp to the forms, instead of being outside as TEI proposes, looks interesting.

Nevertheless, I would not add a different version for the male. That one would be in the lemma, and have only one inflected form.

It is clear that, when inflecting, everything should be inherited from the lemma, but replacing whatever is specifically mentioned (in this case, the genre).

**Comment by ttasovac** [comment]
Hi @ambs, lexical vs. editorial view is a big challenge for retrodigitized dictionaries. While I would also prefer that we always go for the lexical view, we cannot really enforce it 100% in TEI Lex-0 because some projects will insist on being able to represent accurately the dictionary as it appears in its print edition. Beauty is in the eyes of the encoder 😄. 

If you can go with the lexical view with the DACL, I'd be all in favor of it, but that would also mean changing the order in which elements appear OR you would have to do some additional transformations to display things as they were in the original dictionary, but I'm not sure how sustainable that is.

P.S. We haven't met yet in person, but I know you through Ana and let me just say how delighted I am that you're helping out with the conversion of the DACL. I'm also a big fan of the eXist-based backend you built for the Academy!

**Comment by ambs** [comment]
Hi, @ttasovac. I hope we meet someday. Who knows on eLex conference.

Regarding display vs content, I understand the struggle. I remember learning MathML, and finding it awful to see the its display encoding (and for math, that is something so formal, it makes less sense than for a dictionary).

For DACL, as we are not aiming to display it exactly as it was printed, I prefer to go for the structural encoding, even if then I need to rework the XML to print it properly. :-)

**Comment by anacastrosalgado** [comment]
My dears @laurentromary and @ttasovac 

We must use ```<gram type="pos">``` or we can use just ```<pos>```?

 ```
<entry type="derivativeWord">
<form type="lemma">
<orth>ensonado</orth>
<form type="lemma">
<orth>ensonado</orth>
<gramGrp>
<gram type="pos" ud:norm “NOUN”>n.</gram>
<gram type="gen">f.</gram>
</gramGrp>
</form>
<form type="inflected">
<orth>ensonado</orth>
<gramGrp>
<gram type="gen">m.</gram>
</gramGrp>
</form>
<form type="inflected">
<orth>ensonada</orth>
<gramGrp>
<gram type="gen">f.</gram>
</gramGrp>
</form>
</entry>
```

@ambs

**Comment by laurentromary** [comment]
Well... Since you ask. TEI Lex 0 recommends the  `gram` version when transforming data into a single target format (e.g. for the Elexis use case). This is too disruptive to my view and would strongly advocate to keep `<pos>`. :-}

**Comment by ambs** [comment]
I would go for

`````
<gram>
    <pos>n.</pos>
    <gen>m.</gen>
</gram>
````

and when there are distinct POS, use

````
<gramGrp>
   <gram>
      <pos>n.</pos>
      <gen>m.</gen>
   </gram>
   <gram>
      <pos>adj.</pos>
   </gram>
</gramGrp>
````

Looks good?

**Comment by anacastrosalgado** [comment]
Thanks, @laurentromary . It looks goods for me. And I dont' want to use the Universal Dependencies Part-of-Speech Tagset. The DACL has some categories that doesn't appear in this classification. I agree with @ambs .

**Comment by iljackb** [comment]
You can’t have these elements inside <gram>.

When there are 2 or more POS for an entry, you can do one of two things:

1) put the grammar information inside <sense>

         <entry>

            ….
            <sense n="1">
               <gramGrp>
                  <pos>n.</pos>
                  <gen>m.</gen>
               </gramGrp>
               ….
            </sense>
            <sense n="2">
               <gramGrp>
                  <pos>adj.</pos>
               </gramGrp>
               ….
            </sense>
         </entry>


2) you can just have multiple <gramGrp>’s in a row (the presence of more than one indicated that there are contrasting features between the two)

         <entry>

            ...
            <gramGrp>
                  <pos>n.</pos>
                  <gen>m.</gen>
            </gramGrp>   
           <!— <lbl>here if you want —>
            <gramGrp>
                  <pos>adj.</pos>
            </gramGrp>   
           ….
         </entry>


if you want, you could put a <lbl> between the two to have a function word like “or” “and” etc…

**Comment by anacastrosalgado** [comment]
I think I'd prefer the first option, @iljackb 
Meanwhile, 'I'm going crazy...

**Comment by ambs** [comment]
ok, a sequence of gramGrps look good.
As for lbls, I am running from them.

**Comment by iljackb** [comment]
@Ana Salgado <anacastrosalgado@gmail.com>, good choice the first is the
most conventional way to do it :-)

**Comment by ambs** [comment]
I suspect we will have situations both for having it on different senses, and some other where the same sense will need more than one (and in that situation, use a sequence of gramGrp elements).

@anacastrosalgado, go for it  :)

**Comment by ana** [comment]
hi @iljackb, replying by mail seems to be somehow broken and you're notifying me (@ana) instead of @anacastrosalgado

**Comment by anacastrosalgado** [comment]
I think you can close this issue...

`  <entry type="derivativeWord" xml:lang="pt" xml:id="antepassado.1" n="1">
            <form type="lemma">
               <orth>antepassado</orth>
            </form>
            <form type="inflected">
               <orth>antepassado</orth>
               <pron>ɐ̃tɨpɐsˈadu</pron>
               <gramGrp>
                  <gram type="gen">m.</gram>
               </gramGrp>
            </form>
            <form type="inflected">
               <orth>antepassada</orth>
               <gramGrp>
                  <gram type="gen">f.</gram>
               </gramGrp>
               <pron>ɐ̃tɨpɐsˈadɐ</pron>
            </form>
            <gramGrp>
               <gram type="pos" norm="ADJ">adj.</gram></gramGrp>`

This example shows that when a specific inflected form is featured in the entry it should be clearly defined as an independent form, and have enough information about the inflected type (in this case, that the item is a feminine form). For the grammatical information, the TEI Lex-0 standard suggests the use of the gramGrp tag.
