### ISSUE TITLE
<pc> in <cit> (urgent feedback will be appreciated)

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/lexicalresources#56]
I'm working with Bulgarian and Serbian colleagues on encoding a Latin-Bulgarian and a Latin-Serbian dictionary this week. I just noticed something that seems like an obvious omission to me: 

```xml
<sense n="1" xml:id="JDJ.RLS.obduco.1">
    <lbl>1)</lbl>
    <def xml:lang="sr">повести што на што или против чега</def>
    <pc>:</pc>
    <cit type="example">
        <quote>о. exercitum ad oppidum</quote>
    </cit>
    <pc>;</pc>
    <cit type="example">
        <quote>о. Curium</quote>
        <pc>,</pc><!-- not allowed-->
        <cit type="translation" xml:lang="sr">
            <quote>поставити Курија као такмаца другим кандидатима</quote>
        </cit>
    </cit>
    <pc>.</pc>
    <lbl>Отуда</lbl>
    <cit type="example">
        <quote>о. posterum diem</quote>
        <pc>,</pc><!-- not allowed-->
        <cit type="translation">
            <quote>додати и други дан</quote>
        </cit>
    </cit>
    <pc>.</pc>
</sense>
```
At the moment, in TEI Lex-0: `<pc>` is not allowed inside a `<cit>`. This makes no sense because we fought to allow `<pc>` within `<entry>` (and we got the change through the TEI Council) because we argued that `<pc>` is used in dictionaries as a structural delimiter or divider between different elements.

`<pc>` plays the same role in `<cit>` —  it separates the quote from the translation. Free text is not allowed in cit anyway, so we really should allow `<pc>`.

Can I get an amen for this?

**Comment by laurentromary** [comment]
This is an easy one to my view and you get a +1 immediately. My proposal would be to adapt the content model of `<cit>` to contain `model.segLike`, which would generalize your proposal nicely (having various types of seg-like object.

**Comment by laurentromary** [comment]
I agreed, we could probably make a TEI ticket on this.

**Comment by ttasovac** [comment]
Cool. I will implement this on our end later in the day and create a TEI ticket.

**Comment by ttasovac** [comment]
I will close this, but keep in mind that I've opened up a ticket for the Council on this: https://github.com/TEIC/TEI/issues/1891. You may want to go and give a 👍 to it to show support.
