### ISSUE TITLE
text in sense - do we really want it?

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/lexicalresources#57]
In the following example, please note my professionally phrased comments inside `<sense>`.  Currently, we allow free text inside `sense`.

```xml
<sense n="1" xml:id="JDJ.RLS.obduco.1"><lbl>1)</lbl>
    <def xml:lang="sr">повести што на што или против чега</def><pc>:</pc>
    <cit type="example">
        <quote>о. exercitum ad oppidum</quote>
    </cit>; <!--yuck-->
    <cit type="example">
        <quote>о. Curium</quote>
        <pc>,</pc>
        <cit type="translation" xml:lang="sr">
            <quote>поставити Курија као такмаца другим кандидатима</quote>
        </cit>
    </cit>. <!--yuck-->
    <lbl>Отуда</lbl>
    <cit type="example">
        <quote>о. posterum diem</quote>
        <pc>,</pc>
        <cit type="translation">
            <quote>додати и други дан</quote>
        </cit>
    </cit>.<!--yuck-->
</sense>
```
How do we feel about it? My sense that mixed content should be avoided here. The question is: do we only strongly suggest this in the narrative or do we get rid of free text in `sense`? 

If somebody can come up with examples why we _should_ allow free text in sense, I'd much appreciate it. I can't think of any right now but that doesn't mean there isn't one.

**Comment by laurentromary** [comment]
This is why we generalized the availability of `<pc>` and `<lbl>`.  We could change the content model of `<sense>` to:
`<content>
 <alternate minOccurs="0"
  maxOccurs="unbounded">
   <elementRef key="sense"/>
  <classRef key="model.entryPart.top"/>
  <classRef key="model.phrase"/>
  <classRef key="model.global"/>
 </alternate>
</content>`

**Comment by ttasovac** [comment]
Cool. Will implement later today.

**Comment by ttasovac** [comment]
Closing this because it's been implemented.
