### ISSUE TITLE
Revisiting note and dictScrap

### ISSUE THREAD

**Issue by sarampcarvalho** [DARIAH-ERIC/lexicalresources#60]
At the Lisbon TEI Masterclass I am encoding an example entry for the upcoming Dictionary of Endometriosis. The entry contains a definition and an additional explanatory note. I understand that note has become deprecated in TEI-Lex0, but dictScrap is currently also not allowed inside a sense.

Furthermore, I am not sure that dictScrap would be appropriate here, because this really is a further expansion on the definition (i.e. it depicts a subtype of the notion being defined) and not some unspecified content.

```xml
<entry xml:id="DicEndo.hysterectomy" xml:lang="en">
    <form type="lemma">
        <orth>Hysterectomy</orth>
        <pron><pc>/</pc>ˌhɪstəˈrektəmi<pc>/</pc></pron>
    </form>
    <gramGrp>
        <gram type="pos">noun</gram>
    </gramGrp>
    <sense xml:id="DicEndo.hysterectomy.1">
        <def>Surgical removal of the uterus.</def>
        <!--note is not allowed, but I'm not sure that dictScrap is expressive enough.-->
        <note>When the ovaries and the fallopian tubes are also removed, it is called hysterectomy
            with bilateral salpingo-oopherectomy.</note>
    </sense>
</entry>
```
I'd appreciate some feedback whenever possible.
Best regards,
Sara Carvalho

**Comment by laurentromary** [comment]
I would tend to allow `<note>` to occur. This complements nicely `<def>` in your example.

**Comment by GuidaRamos** [comment]
Having note would be very helpful for the encoding in terminological dictinaries, because ISO definitions can be accompanied by an explicit note. See attched example.
![colmated natural cork stopper](https://user-images.githubusercontent.com/36055684/60618442-1ef97700-9dce-11e9-8cd2-150b4bc58dbb.png)
Thanking you, my best regards,
Margarida

**Comment by ttasovac** [comment]
I couldn't agree more. We'll bring back `note`!

**Comment by ttasovac** [comment]
@laurentromary will you have a moment to implement this tonight? or should I do look into in the morning?

**Comment by laurentromary** [comment]
See if it is done when you wake up!

Envoyé de mon iPhone

**Comment by ttasovac** [comment]
Merci, Laurent! 

A "note" :) for @sarampcarvalho and @GuidaRamos. The newly compiled version of the TEI Lex-0  schema is not yet in our workshop repository. I will add it later during the day (in case we make some more changes in the meantime) and then you'll have to do the whole shebang of merging from upstream to get the latest version. But we can do this at the beginning of the class today...

**Comment by sarampcarvalho** [comment]
Thank you @laurentromary and @ttasovac! 
"Note" taken! :)

**Comment by GuidaRamos** [comment]
Thank you all !!

Enviado do Correio para Windows 10

De: Toma Tasovac
Enviado: 4 de julho de 2019 09:11
Para: DARIAH-ERIC/lexicalresources
Cc: Guida; Mention
Assunto: Re: [DARIAH-ERIC/lexicalresources] Revisiting note and dictScrap(#60)

Merci, Laurent!
A "note" :) for @sarampcarvalho and @GuidaRamos. The newly compiled version of the TEI Lex-0 schema is not yet in our workshop repository. I will add it later during the day (in case we make some more changes in the meantime) and then you'll have to do the whole shebang of merging from upstream to get the latest version. But we can do this at the beginning of the class today...
