### ISSUE TITLE
Problem with XML schema definition generated from TEILex0-ODD.xml - model is not deterministic

### ISSUE THREAD

**Issue by tklampfl** [DARIAH-ERIC/lexicalresources#66]
I tried to evaluate a TEI document against a XSD based on TEILex0-ODD.xml generated with Roma and got an error message:
In Notepad++ with the XML Tools (libXML 2.9.3, libXSTL 1.1.28): 
`the content model is not deterministic`
In Oxygen with Xerxes 1.22.0: 
`"http://www.tei-c.org/ns/1.0":xr and "http://www.tei-c.org/ns/1.0":xr (or elements from their substitution group) violate "Unique Particle Attribution". During validation against this schema, ambiguity would be created for those two particles.`

Steps to reproduce:

1. Create a XML schema definition with ([Roma](https://roma.tei-c.org)) out of TEILex0-ODD.xml.
2. Evaluate a TEI-document (it does not play a role which one) against the Schema.

I want to ask if someone has tried to work with a XSD before? Do I make something wrong?

Thank you for your help!

**Comment by laurentromary** [comment]
This seems to results from the fact that we added `<xr>` in `model.emphLike` to have it in `<def>`. We probably wanted to be too clever here. I am checking a possible mend.

**Comment by laurentromary** [comment]
Corrected in https://github.com/DARIAH-ERIC/lexicalresources/commit/89f49cf0d39c11d4fbcf79a0997a74ad3412eeb1

**Comment by tklampfl** [comment]
It seems to work now. The error does not appear any more.

Thank you for your help!
