### ISSUE TITLE
TEI Lex0: where to start?

### ISSUE THREAD

**Issue by lauma** [DARIAH-ERIC/lexicalresources#67]
Hello, all!

I am interested in converting couple retro-digitized dictionaries from custom in-house XML formats into TEI-Lex0 format, however I strugle to understand, where to start. Could you point me, please, what is the best introduction for understanding how a correct TEI-Lex0 document must be formed and what parts it should/might contain, if I don't have any previous experience with TEI? Some tutorial or should I just go read the full specification? Is this the full specification: https://dariah-eric.github.io/lexicalresources/pages/TEILex0/TEILex0.html#index.xml-body.1_div.7 ? Is there some kind of formal validation tools I could use to check my results? Anything else to improve my understanding?

I appologise, if this is not the right place to ask.

**Comment by laurentromary** [comment]
If you are new to the TEI, you can have a look at the TEI dictionary chapter: https://www.tei-c.org/release/doc/tei-p5-doc/en/html/DI.html and/or read some introductory papers on the subject, such as https://journals.openedition.org/jtei/522 or https://journals.openedition.org/jtei/540 (sorry :-}), learn through the DARIAH teach course: https://teach.dariah.eu/course/view.php?id=20 or browse the SSK scenario on the subject (which points to additional resources): http://ssk.huma-num.fr/#/scenarios/SSK_sc_dictionaryInTei

You can also book your agenda on 20-24 April 2020 and submit a proposal to https://dhmc2020.sciencesconf.org and have the opportunity to work on your project face to face.

As to validation, most of us use Oxygen. We can speak off GitHub if you want.
