### ISSUE TITLE
Missing elements in teiHeader

### ISSUE THREAD

**Issue by TomazErjavec** [DARIAH-ERIC/lexicalresources#68]
I just noticed that Lex0 disallows a number of elements from the TEI header which are rather useful, e.g. `<availability>` (can't do without it!), `<projectDesc>` (to say something about the project that enabled the work done), `<classDecl>` (e.g. for taxonomies), `<appInfo>` (to document tools used), and maybe others.

Could these be de-removed?

**Comment by ttasovac** [comment]
Absolutely.

Could you do me a favor and paste some examples for each of these in this thread. We can then look at each of them and include them in the documentation when we revive them in the schema.

--
Belgrade Center for Digital Humanities
http://humanistika.org

**Comment by TomazErjavec** [comment]
> Absolutely.

Thanks @ttasovac, good to hear that.

> Could you do me a favor and paste some examples for each of these in this thread. We can then look at each of them and include them in the documentation when we revive them in the schema.

I think it is easiest if I point you to the resource I was working on when I noticed this: http://nl.ijs.si/et/tmp/kas/BiTerm/kas-biterm.test.xml, which is a draft of a automatically extracted list of bilingual term candidates from a corpus. 
So, the examples are the elements in the header that are commented out, which I had to do so I could validate the file.

PS: and in case there are some comments on the structure of the entries, I am of course happy to receive them!

**Comment by laurentromary** [comment]
I clearly agree. I can implement this as we agree on one element after the other. Let us start with `<availability>`: a clear no-brainer, but we need to add `<licence>` (otherwise, we only have `<p>` there). Green light?

**Comment by ttasovac** [comment]
Mais oui! 
--
Belgrade Center for Digital Humanities
http://humanistika.org

**Comment by laurentromary** [comment]
`<projectDesc>` is already there, but for some reason - even if it does generates a RelaxNG that looks OK - the element does not actually show in `<encodingDesc>`. There is bug and I have not managed to find out where yet...

**Comment by xlhrld** [comment]
> `<projectDesc>` is already there, but for some reason - even if it does generates a RelaxNG that looks OK - the element does not actually show in `<encodingDesc>`. There is bug and I have not managed to find out where yet...

I'd really like to see `encodingDesc/tagsDecl` and especially `encodingDesc/tagsDecl/rendition` up and running. The fact that it's missing may be related to the bug you mentioned, @laurentromary.

**Comment by laurentromary** [comment]
Hurray, I have found the bug! It was `<p>` missing: the element is required at various places in some header sub-components content models. 
I could now add `<tagsDecl>` and `<rendition>` as suggested by @xlhrld if there is no objection from the group.

**Comment by ttasovac** [comment]
> I could now add `<tagsDecl>` and `<rendition>` as suggested by @xlhrld if there is no objection from the group.

👍

**Comment by laurentromary** [comment]
Done. Please check and close when OK.
