### ISSUE TITLE
Cleanup of available elements

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/lexicalresources#7]
Laurent, I was wondering if you could go through the list of available elements (Currently Section 13.1) and try to remove some of the more obvious ones (such as `correspAction`, `correspContext`, `correspDesc`, `table`, `cell`, `row` etc.) from the schema.

We should be conservative for the time being and leave, for instance, anything that has to do with bibl etc. because we still don't have a proper section on how to deal with bibliographic content, both in terms of cit/bibl (Issue #6) and dictionary metadata itself (Issue #8) but we could still reduce the list of available elements by removing those that we are sure won't play any role in TEI Lex 0.

**Comment by laurentromary** [comment]
I have implemented this for the elements you suggested. I leave the ticket opened so that we can add more suggestions here.

**Comment by ttasovac** [comment]
I'm closing this because I'm in a cleaning kind of mood. We can always create new tickets for specific cleaning issues we need to discuss.
