### ISSUE TITLE
Bring back <gloss>!

### ISSUE THREAD

**Issue by laurentromary** [DARIAH-ERIC/lexicalresources#70]
We need it in <cit type="etymon"> for etymological descriptions. This also means we will have to change the content model of `<cit>`: it does not contain <gloss> by default in P5.

**Comment by ttasovac** [comment]
Agreed! We have good examples from the Portuguese dictionaries.

**Comment by anacastrosalgado** [comment]
Dicionário da Língua Portuguesa Contemporânea (2001), Academia das Ciências de Lisboa
abcesso = abscess

![abcesso](https://user-images.githubusercontent.com/45368069/68878408-92f24700-06ff-11ea-9026-1606a582633b.PNG)

` <entry xml:id="abcesso" xml:lang="pt">
            <form type="lemma">
               <orth>abcesso</orth>
               <pron>ɐbsˈεsu</pron>
               <form type="variant" xml:id="id" xml:lang="pt-BR">
                  <pc>,</pc>
                  <orth>abscesso</orth>
                  <pron>ɐbʃsˈεsu</pron>
                  <pc>(</pc>
                  <usg type="geographic">
                     <placeName>Brasil</placeName>
                     <pc>)</pc>
                  </usg>
               </form>
               <gramGrp>
                  <gram type="pos" norm="NOUN">s.</gram>
                  <gram type="gen">m.</gram>
               </gramGrp>
            </form>
            <etym type="inheritance">
               <pc>(</pc>
               <seg type="desc">Do</seg>
               <cit type="etymon">
                  <lang expand="latim">lat.</lang>
                  <form>
                     <orth xml:lang="la">abscessus</orth>
                     <pc>'</pc>
                     <gloss xml:lang="pt">branco</gloss>
                     <pc>'</pc>
                  </form>
               </cit>
               <pc>)</pc>
            </etym> 
            <sense xml:id = "abcesso_sense">
               <def>Acumulação de pus numa cavidade que se forma devido a infecção</def>
               <pc>;</pc>
               <def>inchaço causado por acumulação de pus</def>
               <pc>.</pc>
               <xr type="synonymy"><ref type="entry">apostema</ref></xr>
               <cit type="example"><quote><pc></pc>Tomou antibiótico porque tinha um abcesso num dente<pc>.</pc></quote></cit>
            </sense>
         </entry>`

**Comment by ttasovac** [comment]
done
