### ISSUE TITLE
lbl in bibl

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/lexicalresources#71]
we're using `<bibl type="attestation">` but we can't have a `<lbl>` inside `<bibl>`. Ana will add an example

**Comment by anacastrosalgado** [comment]
Dicionário Eletrônico Houaiss da Língua Portuguesa - CD-ROM
sapato = shoe

` <entry xml:lang="pt-BR" xml:id ="sapato">
![sapato_imagem](https://user-images.githubusercontent.com/45368069/68877692-612cb080-06fe-11ea-83bd-d9d3b969ea67.png)

            <form type="lemma">
               <orth>sapato</orth>
               <gramGrp>
                  <gram type="pos" norm="NOUN">s.</gram>
                  <gram type="gen">m.</gram>
               </gramGrp>
            </form>
            <bibl type="attestation">
               <pc>(</pc>
               <date>sXIII</date>
               <lbl>cf.</lbl>
               <title>AGC</title>
               <pc>)</pc>
            </bibl>
            <sense n="1" xml:id = "sapato_sense1">
               <usg type="domain">VEST</usg>  
               <def>calçado, ger. de sola dura, que cobre o pé, parcial ou completamente ± s. abotinado vest o que vai até à altura do tornozelo</def>
            </sense>
            `
