### ISSUE TITLE
Marking and cross-referencing obsolete / deprecated forms 

### ISSUE THREAD

**Issue by phoenix-mossimo** [DARIAH-ERIC/lexicalresources#73]
Hi all, I have a question concerning the deprecated word forms. We (CCL*) have a number of spellings, which currently include brackets (i.e. "xx(y)xx") and have to be disambiguated into two distinct variants 1) "xxxx"and 2) "xxyxx", which keep the properties of the original form (e.g. attributes, sub-elements). For referencing purposes, however, we would like not to eliminate the original, but to keep it, marking as "deprecated", "obsolete" etc., plus add cross-references to both new and old forms. Considering that the current form "type"-attribute might be occupied already (with e.g. `@type="inflected"`) which is the LEX-0-conform way to fulfill the three tasks?

We were considering the following options (thanks @laurentromary for the feedback):
 
1) Marking the existing form as obsolete / deprecated with a) an extra lable or b) @change/@status attributes:
a) `<form type="inflected"> <lbl>obsolete</lbl>`
b) `<form type="inflected" change="deprecated"> or <form type="inflected" status="deprecated">`

2) Pointing to the new-forms with a) an extra cross-reference or b) @corresp attribute: 
a) `<form type="inflected"><lbl>obsolete</lbl><xr type = "substitutedBy"><ref type=“form” target="#xml_id1 #xml_id2"/></xr>`
b) `<form type="inflected" change="deprecated" corresp="#xml_id1 #xml_id2">`

3) Pointing to the old form with a) an extra cross-reference or b) @corresp attribute:
a) `<form type="inflected"><xr type ="substituting"><ref type=“form” target="#xml_id0"/></xr>`
b) `<form type="inflected" change="new?" corresp="#xml_id0">`

Thanks for the feedback.

*Comprehensive Coptic Lexicon, hosted at BBAW (Thesarus Linguae Aegyptia project). 
Recent Dataset: https://refubium.fu-berlin.de/handle/fub188/24570
Web-Interface: http://coptic-dictionary.org/

**Comment by laurentromary** [comment]
My favorite would be `<form type="inflected" status="deprecated" corresp="#xml_id1 #xml_id2">`, with a customization of form to make it member of `att.docStatus`.  I have the feeling  that  `<xr>` would be an overkill for this use case. Note that I don't limit my reasoning to the TEI Lex framework (we may not integrate the corresponding customization) but in the TEI framework at  large.

**Comment by TomazErjavec** [comment]
By what @phoenix-mossimo writes, you would use `@type` if it wasn't already used for other purposes. So you could use `form/@subtype` instead.

`@status` to me sounds a bit tag abusive, as, if I understand correctly (cf. https://dariah-eric.github.io/lexicalresources/pages/TEILex0/TEILex0.html#TEI.att.docStatus) it is meant for the status of something in terms of the document workflow. But here, again, if I understand correctly, you are taking about obsolete (archaic?) word-forms.

**Comment by laurentromary** [comment]
There are two aspects here:
- I don't feel at ease when I use two separate dimensions on @type and @subtype, and would thus avoid @subtype to express something that has nothing to do with the first typology ("inflected")
- Although not used (yet) at many places, the semantic of @status is very close to what we want to express with deprecation (see the value "deprecated" in https://tei-c.org/release/doc/tei-p5-doc/fr/html/ref-att.docStatus.html). I have reused this attribute in several project like I suggest here and it has proven (among other things) intuitive for encoders to have it at hand.

**Comment by TomazErjavec** [comment]
> I don't feel at ease when I use two separate dimensions on @type and @subtype

That is a good point (which I haven't taken into consideration in my attemps at converting dictionaries into Lex0, hmm)

> the semantic of @status is very close to what we want

Maybe I misunderstood in which way the forms are "deprecated" but if these are forms in a published 
dictionary, and they used to be spelled "xxyxx" but no longer are (say, because of a spelling reform), then I still think `@status` is dubious: yes, it contains the value "deprecated", but the other values are "draft", "published" etc. surely a different kettle of fish.

**Comment by phoenix-mossimo** [comment]
> * I don't feel at ease when I use two separate dimensions on @type and @subtype, and would thus avoid @subtype to express something that has nothing to do with the first typology ("inflected")

Yes, I agree that `@type` and `@subtype` should not be semantically heterogeneous. 

> `@status` to me sounds a bit tag abusive, as, if I understand correctly (cf. https://dariah-eric.github.io/lexicalresources/pages/TEILex0/TEILex0.html#TEI.att.docStatus) it is meant for the status of something in terms of the document workflow. But here, again, if I understand correctly, you are taking about obsolete (archaic?) word-forms.

I also understood the TEI specification in the way that `@change` and `@status` refer rather to work process, therefore my reservations

> Maybe I misunderstood in which way the forms are "deprecated" but if these are forms in a published
> dictionary, and they used to be spelled "xxyxx" but no longer are (say, because of a spelling reform), then I still think `@status` is dubious: yes, it contains the value "deprecated", but the other values are "draft", "published" etc. surely a different kettle of fish.

Currently published is the form "xx(y)xx", e.g. http://coptic-dictionary.org/entry.cgi?tla=C5355. 
We want to make two forms out of it: 1) ⲟⲩⲟϭⲉ; 2) ⲟⲩⲟⲟϭⲉ

**Comment by phoenix-mossimo** [comment]
Ok, so the solution I have chosen is: 

- Existing form: 
`<form xml:id="CF1">`
 `<usg type="geo">B</usg>`
**`<orth n="2">(ⲙ)ⲃⲣⲉϩⲓ</orth>`**
`</form>`

- Output forms: 
**`<form   xml:id="CF1" status="deprecated"   corresp="CF2 CF3">`**
`<usg   type="geo">B</usg>`
**`<orth n="2">(ⲙ)ⲃⲣⲉϩⲓ</orth>`**
`</form>`
**`<form xml:id="CF2" corresp="CF1">`**
`<usg   type="geo">B</usg>` 
**`<orth n="2">ⲙⲃⲣⲉϩⲓ</orth>`**
`</form>`
**`<form xml:id="CF3" corresp="CF1">`**    
`<usg   type="geo">B</usg>`
**`<orth n="2">ⲃⲣⲉϩⲓ</orth>`**
`</form>`

**Comment by laurentromary** [comment]
That looks good. I just have a problem with @n having twice the same value: does it make sense from your editorial point of view?

**Comment by phoenix-mossimo** [comment]
It was a copy-paste. I removed it.
