### ISSUE TITLE
usg/@type value mismatch in ODD vs. documentation

### ISSUE THREAD

**Issue by xlhrld** [DARIAH-ERIC/lexicalresources#74]
In section 6.2 "Types of usage information" of the documentation the closed list of legal values contains `temporal` for Lex-0 where TEI originally features `time`. This is not reflected in the formal schema which still contains `time` and not `temporal`.

There is also still TEI's `lang` as a value in the ODD whereas the documentation says this was removed in Lex-0.

I propose to change `time` to `temporal` and to remove `lang` in the list of values for `usg/@type` to reflect the state of our discussion as presented in the documentation.

**Comment by laurentromary** [comment]
That would be an easy fix. Do we have a trace of the actual decision (time vs. temporal). "time" also appears in the Flussschifffahrt example. @ttasovac do you validate this?

Concerning "lang": it does not appear in the schema, but I do see "language": anyone remembers where we got it from?

We should actually put a systematic `<desc>` in each `<valItem>`: suggestions welcome!

**Comment by ttasovac** [comment]
- "language" is definitely wrong here and shouldn't be there. I will remove it now and regenerate the schema.
- we actually, at one point, decided to keep "time" because it's simpler than temporal. I prefer to keep it that way.

**Comment by ttasovac** [comment]
> We should actually put a systematic `<desc>` in each `<valItem>`: suggestions welcome!

Absolutely. @anacastrosalgado and I have a paper where we defined these, so I will add them as well

**Comment by ttasovac** [comment]
Fixed with https://github.com/DARIAH-ERIC/lexicalresources/commit/e31cafed6e34ab0ffa33ead60e5cd0ef361e122a

@anacastrosalgado when you have a moment, could you please send me caixa-de-óculos and Primavera from our ASIALEX paper, not as an image but in XML, I want to add them to the TEI Lex-0 documentation. You can email them to me...

**Comment by xlhrld** [comment]
Perfect, thanks.
