### ISSUE TITLE
References to attestation

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/lexicalresources#9]
> We need to discuss the possible reference to attestation and link this to LMF (part 1 - or rather 2?)

@laurentromary This was your comment in the Google Doc. I'm not sure what to do with it. It was placed in Section on Dictionary Models vs. XML Serialization where we discussed how `<cit>` can be used to mean different things in different situations. 

I've removed your comment from the main text, but I leave it here so that we don't forget it. Let me know what this was about and whether we should still pursue this.

**Comment by laurentromary** [comment]
Since LMF has simplified its "Example" class and allowed "Bibliography" to appear all over the place without making a specific distinction for Attestations, this issue is no issue anymore.
